[tool.poetry]
name = "exdbproject"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.5"
Django = "<1.10"
django-silk = "<2.0"
psycopg2 = {version = "<2.9", optional = true}
uWSGI = {version = "^2.0.31", optional = true}
django-auth-ldap = {version = "<1.3", optional = true}
django-auth-sgf = { git = "file:///mnt/repo/django-auth-sgf", optional = true }

[tool.poetry.dev-dependencies]
nodeenv = ">=1.6"
colorama = ">=0.4.5"
coverage = ">=5.5"
selenium = ">=3.141"
python-auto-mock = "^0.1.1"
pylint = ">=2.6.2,<2.7.0"

[tool.poetry.extras]
prod = ["psycopg2", "uWSGI", "django-auth-ldap", "django-auth-sgf"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
