# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-12-15 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'exdb', '0001_initial'), (b'exdb', '0002_auto_20151215_1948')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('goal', models.TextField(blank=True, null=True)),
                ('guest', models.CharField(blank=True, max_length=300, null=True)),
                ('guest_office', models.CharField(blank=True, max_length=300, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'dr', b'Draft'), (b'pe', b'Pending'), (b'ap', b'Approval'), (b'de', b'Denied'), (b'ad', b'Approved'), (b'co', b'Completed'), (b'ca', b'Cancelled')], default=b'dr', max_length=2)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Audience')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.User')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='exdb.Experience')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='keywords',
            field=models.ManyToManyField(to=b'exdb.Keyword'),
        ),
        migrations.AddField(
            model_name='experience',
            name='planners',
            field=models.ManyToManyField(blank=True, related_name='planner_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='recognition',
            field=models.ManyToManyField(to=b'exdb.Organization'),
        ),
        migrations.AddField(
            model_name='experience',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.SubType'),
        ),
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Type'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='goal',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='guest',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='guest_office',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
