# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-12-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('goal', models.TextField(blank=True, null=True)),
                ('guest', models.CharField(blank=True, max_length=300, null=True)),
                ('guest_office', models.CharField(blank=True, max_length=300, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'dr', b'Draft'), (b'pe', b'Pending'), (b'ap', b'Approval'), (b'de', b'Denied'), (b'ad', b'Approved'), (b'co', b'Completed'), (b'ca', b'Cancelled')], default=b'dr', max_length=2)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Audience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='experiencecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.User'),
        ),
        migrations.AddField(
            model_name='experiencecomment',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='exdb.Experience'),
        ),
        migrations.AddField(
            model_name='experience',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.User'),
        ),
        migrations.AddField(
            model_name='experience',
            name='keywords',
            field=models.ManyToManyField(to='exdb.Keyword'),
        ),
        migrations.AddField(
            model_name='experience',
            name='planners',
            field=models.ManyToManyField(related_name='planner_set', to='exdb.User'),
        ),
        migrations.AddField(
            model_name='experience',
            name='recognition',
            field=models.ManyToManyField(to='exdb.Organization'),
        ),
        migrations.AddField(
            model_name='experience',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.SubType'),
        ),
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Type'),
        ),
    ]
