# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_sent_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='last_evaluation_email_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='needs_author_email',
            field=models.BooleanField(default=False),
        ),
    ]
