# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Temp',
        ),
        migrations.RenameModel(
            old_name='SubType',
            new_name='Type',
        ),
        migrations.RenameModel(
            old_name='Temp',
            new_name='Subtype',
        ),

        migrations.RenameField(
            model_name='experience',
            old_name='type',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='sub_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='temp',
            new_name='subtype',
        ),
    ]
