# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0002_swap_type_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='goal',
            new_name='goals',
        ),
        migrations.AddField(
            model_name='experience',
            name='funds',
            field=models.CharField(blank=True, choices=[('na', 'Not necessary'), ('y', 'Yes, but request not submitted yet'), ('ys', 'Yes, request submitted'), ('ya', 'Yes, request approved')], max_length=2),
        ),
        migrations.AlterField(
            model_name='experience',
            name='conclusion',
            field=models.TextField(blank=True, help_text='What went well? What would change about this experience in the future?'),
        ),
    ]
