# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exdb', '0002_auto_20151217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='approved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='type',
            name='needs_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='audience',
            field=models.CharField(choices=[('b', 'Building'), ('c', 'Campus'), ('f', 'Floor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='experience',
            name='guest',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='experience',
            name='guest_office',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('dr', 'Draft'), ('pe', 'Pending Approval'), ('de', 'Denied'), ('ad', 'Approved'), ('co', 'Completed'), ('ca', 'Cancelled')], default='dr', max_length=2),
        ),
    ]
