# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0003_auto_20160725_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_log', to='exdb.Experience')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
