# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0002_experienceedit'),
        ('exdb', '0003_auto_20160427_0206'),
    ]

    operations = [
    ]
