# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0003_auto_20160725_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='goal',
            new_name='goals',
        ),
        migrations.AddField(
            model_name='experience',
            name='funds',
            field=models.CharField(choices=[('na', 'Not necessary'), ('yn', 'Yes, but request not submitted yet'), ('ys', 'Yes, request submitted'), ('ya', 'Yes, request approved')], default='na', max_length=2),
        ),
        migrations.AlterField(
            model_name='experience',
            name='conclusion',
            field=models.TextField(blank=True, help_text='What went well? What would you change about this experience in the future?'),
        ),
    ]
