# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0003_auto_20160106_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='experience',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='audience',
            field=models.CharField(blank=True, choices=[('b', 'Building'), ('c', 'Campus'), ('f', 'Floor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='exdb.Keyword'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='recognition',
            field=models.ManyToManyField(blank=True, to='exdb.Organization'),
        ),
    ]
