# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exdb', '0004_auto_20160208_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='approver',
            new_name='current_approver',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='approved_timestamp',
        ),
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('de', 'Denied'), ('dr', 'Draft'), ('pe', 'Pending Approval'), ('ad', 'Approved'), ('co', 'Completed'), ('ca', 'Cancelled')], default='dr', max_length=2),
        ),
        migrations.AddField(
            model_name='experienceapproval',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_queue', to='exdb.Experience'),
        ),
    ]
