# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0005_swap_type_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='funds',
            field=models.CharField(choices=[('na', 'Not necessary'), ('yn', 'Yes, but request not submitted yet'), ('ys', 'Yes, request submitted'), ('ya', 'Yes, request approved')], default='na', max_length=2),
        ),
    ]
