# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0005_swap_type_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='temp_subtpyes',
            field=models.ManyToManyField(blank=True, related_name='subtype_set', to='exdb.Subtype'),
        ),
    ]
