# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0005_swap_type_subtype'),
        ('exdb', '0004_experienceedit'),
    ]

    operations = [
    ]
