# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exdb', '0005_auto_20160225_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('related_object_id', models.PositiveIntegerField(null=True)),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_sent_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('emails', models.ManyToManyField(to='exdb.Email')),
            ],
        ),
    ]
