# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0005_swap_type_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='subtype',
        ),
        migrations.AddField(
            model_name='experience',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='exdb.Subtype'),
        ),
    ]
