# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0007_swap_to_temp_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='temp_subtpyes',
            new_name='subtypes',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='subtype',
        ),
    ]
