# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-13 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0008_auto_20161024_1350'),
        ('exdb', '0006_merge'),
    ]

    operations = [
    ]
