# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0008_auto_20161024_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_needed', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='exdbuser',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exdb.Section'),
        ),
        migrations.AlterField(
            model_name='exdbuser',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exdb.Affiliation'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Semester'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Subtype'),
        ),
    ]
