# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-12 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0009_auto_20170811_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('order_number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('m', 'Multiple'), ('f', 'Free Form')], default='f', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='survey_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='experience',
            name='survey_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='funds',
            field=models.CharField(choices=[('na', 'Not necessary'), ('yn', 'Yes, but request not submitted yet'), ('ss', 'Yes, requesting SSI funds'), ('ys', 'Yes, request submitted'), ('ya', 'Yes, request approved')], default='na', max_length=2),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Question'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Experience'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Ballot'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Choice'),
        ),
    ]
