# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0009_auto_20170811_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='valid_subtypes',
            field=models.ManyToManyField(blank=True, to='exdb.Subtype'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='funds',
            field=models.CharField(choices=[('na', 'Not necessary'), ('yn', 'Yes, but request not submitted yet'), ('ss', 'Yes, requesting SSI funds'), ('ys', 'Yes, request submitted'), ('ya', 'Yes, request approved')], default='na', max_length=2),
        ),
    ]
