# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0009_auto_20170811_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('original_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='funds',
            field=models.CharField(choices=[('na', 'Not necessary'), ('yn', 'Yes, but request not submitted yet'), ('ss', 'Yes, requesting SSI funds'), ('ys', 'Yes, request submitted'), ('ya', 'Yes, request approved')], default='na', max_length=2),
        ),
        migrations.AddField(
            model_name='publication',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exdb.Experience'),
        ),
    ]
