# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0010_auto_20171005_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='survey_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
