# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0011_experience_survey_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='survey_code',
            field=models.CharField(max_length=6),
        ),
    ]
