# Generated by Django 2.2.28 on 2026-07-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0012_auto_20260729_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtype',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
