# Generated by Django 2.2.28 on 2026-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exdb', '0013_auto_20260731_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='recognition',
            field=models.ManyToManyField(blank=True, to='exdb.Section', verbose_name='Building/Floor'),
        ),
    ]
